// File generated by FlutterFire CLI.
// This is a PLACEHOLDER file.
// Run: flutterfire configure --project=YOUR_PROJECT_ID
// to generate the actual configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'Only Android is supported for this MVP.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA81vHD1OouE3sPLzmgDUS_OH1waade5aY',
    appId: '1:1881105365:web:9a016b072ff0b3c59ed35c',
    messagingSenderId: '1881105365',
    projectId: 'vedo-01',
    authDomain: 'vedo-01.firebaseapp.com',
    storageBucket: 'vedo-01.firebasestorage.app',
    measurementId: 'G-04PSF0JH5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsiK_6dwsFW9Dbin29Keeilla-xGO8mfI',
    appId: '1:1881105365:android:60db292185724adc9ed35c',
    messagingSenderId: '1881105365',
    projectId: 'vedo-01',
    storageBucket: 'vedo-01.firebasestorage.app',
  );

}